-- Útfæra schema
CREATE TABLE [IF NOT EXISTS] EVENTS (
  EVENT_ID SERIAL PRIMARY KEY,
  EVENT_NAME VARCHAR(64) NOT NULL,
  SLUG VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(64),
  CREATED TIMESTAMP,
  UPDATED TIMESTAMP
);

CREATE TABLE [IF NOT EXISTS] REGISTRATIONS (
  REGISTRATION ID SERIAL PRIMARY KEY,
  REGISTRATION_NAME VARCHAR(64) NOT NULL,
  COMMENT VARCHAR(128),
  EVENT_ID INTEGER FOREIGN KEY REFERENCES EVENTS(EVENT_ID),
  CREATED TIMESTAMP
);

CREATE TABLE [IF NOT EXISTS] USERS (
  USER_ID SERIAL PRIMARY KEY,
  USERNAME VARCHAR(64),
  USER_PASSWORD VARCHAR(256)
);
